baseurl = "https://shizuki.moe"
languageCode = "zh-cn"
title = "Shizukiの魔法小屋"

defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

enableGitInfo = true

[frontmatter]
lastmod = ['lastmod', ':git', 'date']

[pagination]
pagerSize = 5
