[[social]]
name = "Bangumi"
url = "https://bgm.tv/user/shizukinatsuki"

[social.params]
icon = "brand-bangumi"

[[social]]
name = "BiliBili"
url = "https://space.bilibili.com/3546607333149385"

[social.params]
icon = "brand-bilibili"

[[social]]
name = "GitHub"
url = "https://github.com/ShizukiNatsuki"

[social.params]
icon = "brand-github"

[[social]]
name = "Steam"
url = "https://steamcommunity.com/id/ShizukiNatsuki/"

[social.params]
icon = "brand-steam"

[[social]]
name = "X"
url = "https://x.com/ShizukiNatsuki"

[social.params]
icon = "brand-x"
