mainSections = ["post"]
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2025
customText = ""

[dateFormat]
published = "2006.01.02"
lastUpdated = "2006.01.02 15:04"

[sidebar]
emoji = "❄️"
subtitle = "可愛いは正義です"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "CC BY-NC-SA 4.0"

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "ShizukiMoe/Comment"
repoID = "R_kgDOPbH3Ww"
category = "Comment"
categoryID = "DIC_kwDOPbH3W84Ct-mn"
mapping = "pathname"
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0
